// WGSL Compute Shader: Quantum Probability Wave Psi(x,t) in Order-Book Potential Well
struct PsiParams {
  gridSize: u32,
  dt: f32,
  dx: f32,
  hbar: f32,
  mass: f32,
  centerPrice: f32,
  waveVelocity: f32,
  timeElapsed: f32,
};

struct PotentialNode {
  price: f32,
  barrierHeight: f32, // liquidity wall resistance
};

@group(0) @binding(0) var<uniform> params: PsiParams;
@group(0) @binding(1) var<storage, read> potentials: array<PotentialNode>; // liquidity walls
@group(0) @binding(2) var<storage, read_write> psiReal: array<f32>; // Re[Psi]
@group(0) @binding(3) var<storage, read_write> psiImag: array<f32>; // Im[Psi]
@group(0) @binding(4) var<storage, read_write> probDensity: array<f32>; // |Psi|^2

@compute @workgroup_size(64)
fn main(@builtin(global_invocation_id) global_id: vec3<u32>) {
  let idx = global_id.x;
  if (idx >= params.gridSize) {
    return;
  }

  let x = (f32(idx) - f32(params.gridSize) * 0.5) * params.dx;
  let price = params.centerPrice + x;

  // Potential field V(x) generated by liquidity clusters
  var potentialV: f32 = 0.0;
  for (var i: u32 = 0u; i < arrayLength(&potentials); i = i + 1u) {
    let pNode = potentials[i];
    let dist = (price - pNode.price);
    potentialV = potentialV + pNode.barrierHeight * exp(-0.5 * (dist * dist) / 4.0);
  }

  // Wavepacket dispersion with phase modulation
  let k0 = params.waveVelocity * params.mass / params.hbar;
  let sigma = 6.0;
  let envelope = exp(-0.5 * (x * x) / (sigma * sigma));
  let phase = k0 * x - (params.hbar * k0 * k0 / (2.0 * params.mass)) * params.timeElapsed;

  // Damped by potential barrier (quantum barrier penetration / reflection)
  let tunnelingFactor = exp(-sqrt(max(potentialV - 0.5, 0.0)) * 0.8);

  let realVal = envelope * cos(phase) * tunnelingFactor;
  let imagVal = envelope * sin(phase) * tunnelingFactor;

  psiReal[idx] = realVal;
  psiImag[idx] = imagVal;
  probDensity[idx] = realVal * realVal + imagVal * imagVal;
}
